import React from "react";

export const initialData =
    [
        {
            url: "./components/img/Group.svg",
            name: "AOS средство для мытья посуды Crystal",
            sizeType: "450мл",
            size: "450мл",
            barcode: "4604049097548",
            manufacturer: "Нэфис",
            brand: "Dan Jukes",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
            price: 48.76,
        },
        {
            url: "Molecule Man",
            name: "ARIEL Автмат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник",
            sizeType: "15X28.8 г",
            size: "15X28.8 г",
            barcode: "4604049097548",
            manufacturer: "Нэфис",
            Brand: "AOS",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
            price: 48.76,
        },
        {
            url: "Molecule Man",
            name: "BIMAX Порошок стиральный Автомат 100 пятен COMPACT",
            sizeType: "1500 г",
            size: "1500 г",
            barcode: "4604049097548",
            manufacturer: "Нэфис",
            Brand: "AOS",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
            price: 48.76,
        },
        {
            url: "kkk",
            name: "AOS средство для мытья посуды Crystal",
            sizeType: "450мл",
            size: "450мл",
            barcode: "4604049097548",
            manufacturer: "Нэфис",
            brand: "Dan Jukes",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
            price: 48.76,
        },
        {
            url: "Molecule Man",
            name: "ARIEL Автмат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник",
            sizeType: "15X28.8 г",
            size: "15X28.8 г",
            barcode: "4604049097548",
            manufacturer: "Нэфис",
            Brand: "AOS",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
            price: 48.76,
        },
        {
            url: "Molecule Man",
            name: "BIMAX Порошок стиральный Автомат 100 пятен COMPACT",
            sizeType: "1500 г",
            size: "1500 г",
            barcode: "4604049097548",
            manufacturer: "Нэфис",
            Brand: "AOS",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
            price: 48.76,
        }, {
            url: "kkk",
            name: "AOS средство для мытья посуды Crystal",
            sizeType: "450мл",
            size: "450мл",
            barcode: "4604049097548",
            manufacturer: "Нэфис",
            brand: "Dan Jukes",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
            price: 48.76,
        },
        {
            url: "Molecule Man",
            name: "ARIEL Автмат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник",
            sizeType: "15X28.8 г",
            size: "15X28.8 г",
            barcode: "4604049097548",
            manufacturer: "Нэфис",
            Brand: "AOS",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
            price: 48.76,
        },
        {
            url: "Molecule Man",
            name: "BIMAX Порошок стиральный Автомат 100 пятен COMPACT",
            sizeType: "1500 г",
            size: "1500 г",
            barcode: "4604049097548",
            manufacturer: "Нэфис",
            Brand: "AOS",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
            price: 48.76,
        }, {
            url: "kkk",
            name: "AOS средство для мытья посуды Crystal",
            sizeType: "450мл",
            size: "450мл",
            barcode: "4604049097548",
            manufacturer: "Нэфис",
            brand: "Dan Jukes",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
            price: 48.76,
        },
        {
            url: "Molecule Man",
            name: "ARIEL Автмат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник",
            sizeType: "15X28.8 г",
            size: "15X28.8 г",
            barcode: "4604049097548",
            manufacturer: "Нэфис",
            Brand: "AOS",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
            price: 48.76,
        },
        {
            url: "Molecule Man",
            name: "BIMAX Порошок стиральный Автомат 100 пятен COMPACT",
            sizeType: "1500 г",
            size: "1500 г",
            barcode: "4604049097548",
            manufacturer: "Нэфис",
            Brand: "AOS",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
            price: 48.76,
        }, {
            url: "kkk",
            name: "AOS средство для мытья посуды Crystal",
            sizeType: "450мл",
            size: "450мл",
            barcode: "4604049097548",
            manufacturer: "Нэфис",
            brand: "Dan Jukes",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
            price: 48.76,
        },
        {
            url: "Molecule Man",
            name: "ARIEL Автмат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник",
            sizeType: "15X28.8 г",
            size: "15X28.8 г",
            barcode: "4604049097548",
            manufacturer: "Нэфис",
            Brand: "AOS",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
            price: 48.76,
        },
        {
            url: "Molecule Man",
            name: "BIMAX Порошок стиральный Автомат 100 пятен COMPACT",
            sizeType: "1500 г",
            size: "1500 г",
            barcode: "4604049097548",
            manufacturer: "Нэфис",
            Brand: "AOS",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
            price: 48.76,
        }, {
            url: "kkk",
            name: "AOS средство для мытья посуды Crystal",
            sizeType: "450мл",
            size: "450мл",
            barcode: "4604049097548",
            manufacturer: "Нэфис",
            brand: "Dan Jukes",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
            price: 48.76,
        },
        {
            url: "Molecule Man",
            name: "ARIEL Автмат Гель СМС жидкое в растворимых капсулах Liquid Capsules Горный родник",
            sizeType: "15X28.8 г",
            size: "15X28.8 г",
            barcode: "4604049097548",
            manufacturer: "Нэфис",
            Brand: "AOS",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
            price: 48.76,
        },
        {
            url: "Molecule Man",
            name: "BIMAX Порошок стиральный Автомат 100 пятен COMPACT",
            sizeType: "1500 г",
            size: "1500 г",
            barcode: "4604049097548",
            manufacturer: "Нэфис",
            Brand: "AOS",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam interdum ut justo, vestibulum sagittis iaculis iaculis. Quis mattis vulputate feugiat massa vestibulum duis. Faucibus consectetur aliquet sed pellentesque consequat consectetur congue mauris venenatis. Nunc elit, dignissim sed nulla ullamcorper enim, malesuada.",
            price: 48.76,
        },

    ]


